language: go
sudo: false

services:
  - docker
  
matrix:
  include:
  #- os: osx
  #  go: 1.14.x  
  - os: linux
    dist: focal
    arch: amd64
    go: 1.14.x
  - os: linux
    dist: focal
    arch: arm64
    go: 1.14.x
      
notifications:
  email: false

script:
  - docker login -u bhumikapaharia10 -p Root123!@#
  - curl -sL https://taskfile.dev/install.sh | sh
  #- travis_wait 40 ./bin/task docker 2> /dev/null
  - ./bin/task ci
