language: go
sudo: false

os: linux
dist: focal
go: 1.14.x

arch:
  - amd64
  - arm64
  
services:
  - docker
  
#matrix:
#  include:
#  - os: osx
#    go: 1.14.x  
#  - os: linux
#    arch: amd64
#    go: 1.14.x
#  - os: linux
#    arch: arm64
#    go: 1.14.x
      
notifications:
  email: false

script:
  - curl -sL https://taskfile.dev/install.sh | sh
  - ./bin/task ci
  
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      docker login -u bhumikapaharia10 -p Root123!@# ;
      if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
        if [ -n "${tag}" ];then
          ./bin/task tag=${TRAVIS_TAG} arch=$GOARCH docker ;
          docker tag {{.DOCKER_REPO}}:dev {{.DOCKER_REPO}}:dev-arm64 ;
          docker push {{.DOCKER_REPO}}:dev-arm64 ;
        fi
      else
        if [ -n "${tag}" ];then
          ./bin/task tag=${TRAVIS_TAG} arch="" docker ;
          docker tag {{.DOCKER_REPO}}:dev {{.DOCKER_REPO}}:dev-amd64 ;
          docker push {{.DOCKER_REPO}}:dev-amd64 ;
        fi
      fi
    fi
  
  #- if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
  #    docker login -u bhumikapaharia10 -p Root123!@# ;
  #    export tag=0.23.0 ;
  #    echo $tag ;
  #    ./bin/task tag=0.23.0 docker ;
  #  fi
    
    #./bin/task tag=${TRAVIS_TAG} arch="arm64" docker ;
      #if [ -n "${TRAVIS_TAG}" ]; then
      #  tag = ${TRAVIS_TAG} ;
      #fi
