language: go
sudo: false

services:
  - docker
  
matrix:
  include:
  - os: osx
    go: 1.14.x  
  - os: linux
    arch: amd64
    go: 1.14.x
  - os: linux
    arch: arm64
    go: 1.14.x
      
notifications:
  email: false

script:
  - echo $TRAVIS_OS_NAME
  #- docker login -u bhumikapaharia10 -p Root123!@#
  #- curl -sL https://taskfile.dev/install.sh | sh
  #- ./bin/task ci
